package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/chunk1.oel", "assets/data/chunk1.oel");
			type.set ("assets/data/chunk1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk10.oel", "assets/data/chunk10.oel");
			type.set ("assets/data/chunk10.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk2.oel", "assets/data/chunk2.oel");
			type.set ("assets/data/chunk2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk3.oel", "assets/data/chunk3.oel");
			type.set ("assets/data/chunk3.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk4.oel", "assets/data/chunk4.oel");
			type.set ("assets/data/chunk4.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk5.oel", "assets/data/chunk5.oel");
			type.set ("assets/data/chunk5.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk6.oel", "assets/data/chunk6.oel");
			type.set ("assets/data/chunk6.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk7.oel", "assets/data/chunk7.oel");
			type.set ("assets/data/chunk7.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk8.oel", "assets/data/chunk8.oel");
			type.set ("assets/data/chunk8.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk9.oel", "assets/data/chunk9.oel");
			type.set ("assets/data/chunk9.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/dialogue.xml", "assets/data/dialogue.xml");
			type.set ("assets/data/dialogue.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/femboy.txt", "assets/data/femboy.txt");
			type.set ("assets/data/femboy.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/map.oep", "assets/data/map.oep");
			type.set ("assets/data/map.oep", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/start.oel", "assets/data/start.oel");
			type.set ("assets/data/start.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/tile_temple_0.png", "assets/data/tile_temple_0.png");
			type.set ("assets/data/tile_temple_0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_1.png", "assets/data/tile_temple_1.png");
			type.set ("assets/data/tile_temple_1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_2.png", "assets/data/tile_temple_2.png");
			type.set ("assets/data/tile_temple_2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_3.png", "assets/data/tile_temple_3.png");
			type.set ("assets/data/tile_temple_3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_4.png", "assets/data/tile_temple_4.png");
			type.set ("assets/data/tile_temple_4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/aprilfools.png", "assets/images/aprilfools.png");
			type.set ("assets/images/aprilfools.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/batSheet.png", "assets/images/batSheet.png");
			type.set ("assets/images/batSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/clamSheet.png", "assets/images/clamSheet.png");
			type.set ("assets/images/clamSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/echidnaSheet.pdn", "assets/images/echidnaSheet.pdn");
			type.set ("assets/images/echidnaSheet.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/echidnaSheet.png", "assets/images/echidnaSheet.png");
			type.set ("assets/images/echidnaSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/echidnaSheet.txt", "assets/images/echidnaSheet.txt");
			type.set ("assets/images/echidnaSheet.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/edition.png", "assets/images/edition.png");
			type.set ("assets/images/edition.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hotGF.png", "assets/images/hotGF.png");
			type.set ("assets/images/hotGF.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/kirbyGF.png", "assets/images/kirbyGF.png");
			type.set ("assets/images/kirbyGF.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/left_and_right.png", "assets/images/left_and_right.png");
			type.set ("assets/images/left_and_right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/minotaurSheet.png", "assets/images/minotaurSheet.png");
			type.set ("assets/images/minotaurSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mmLogo.png", "assets/images/mmLogo.png");
			type.set ("assets/images/mmLogo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mushSheet.png", "assets/images/mushSheet.png");
			type.set ("assets/images/mushSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/picoDay.png", "assets/images/picoDay.png");
			type.set ("assets/images/picoDay.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/preloaderArt.png", "assets/images/preloaderArt.png");
			type.set ("assets/images/preloaderArt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/slimeSheet.png", "assets/images/slimeSheet.png");
			type.set ("assets/images/slimeSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/sonky.png", "assets/images/sonky.png");
			type.set ("assets/images/sonky.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/spr_player.png", "assets/images/spr_player.png");
			type.set ("assets/images/spr_player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/steveSheet.png", "assets/images/steveSheet.png");
			type.set ("assets/images/steveSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/trimmedAndFixedSprites.png", "assets/images/trimmedAndFixedSprites.png");
			type.set ("assets/images/trimmedAndFixedSprites.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/update-20180603T205106Z-001.zip", "assets/images/update-20180603T205106Z-001.zip");
			type.set ("assets/images/update-20180603T205106Z-001.zip", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/vineSheet.png", "assets/images/vineSheet.png");
			type.set ("assets/images/vineSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/Silverline.mp3", "assets/music/Silverline.mp3");
			type.set ("assets/music/Silverline.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/music/Silverline.ogg", "assets/music/Silverline.ogg");
			type.set ("assets/music/Silverline.ogg", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/music/Silverline.xmp", "assets/music/Silverline.xmp");
			type.set ("assets/music/Silverline.xmp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/flash.wav", "assets/sounds/flash.wav");
			type.set ("assets/sounds/flash.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/roblox_oof.mp3", "assets/sounds/roblox_oof.mp3");
			type.set ("assets/sounds/roblox_oof.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/smack1.mp3", "assets/sounds/smack1.mp3");
			type.set ("assets/sounds/smack1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/smack1.ogg", "assets/sounds/smack1.ogg");
			type.set ("assets/sounds/smack1.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/smack2.mp3", "assets/sounds/smack2.mp3");
			type.set ("assets/sounds/smack2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/smack2.ogg", "assets/sounds/smack2.ogg");
			type.set ("assets/sounds/smack2.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/smack3.mp3", "assets/sounds/smack3.mp3");
			type.set ("assets/sounds/smack3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/smack3.ogg", "assets/sounds/smack3.ogg");
			type.set ("assets/sounds/smack3.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan10.wav", "assets/sounds/Voice/Moan10.wav");
			type.set ("assets/sounds/Voice/Moan10.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan11.wav", "assets/sounds/Voice/Moan11.wav");
			type.set ("assets/sounds/Voice/Moan11.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan12.wav", "assets/sounds/Voice/Moan12.wav");
			type.set ("assets/sounds/Voice/Moan12.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan13.wav", "assets/sounds/Voice/Moan13.wav");
			type.set ("assets/sounds/Voice/Moan13.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan14.wav", "assets/sounds/Voice/Moan14.wav");
			type.set ("assets/sounds/Voice/Moan14.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan15.wav", "assets/sounds/Voice/Moan15.wav");
			type.set ("assets/sounds/Voice/Moan15.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan16.wav", "assets/sounds/Voice/Moan16.wav");
			type.set ("assets/sounds/Voice/Moan16.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan17.wav", "assets/sounds/Voice/Moan17.wav");
			type.set ("assets/sounds/Voice/Moan17.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan4.wav", "assets/sounds/Voice/Moan4.wav");
			type.set ("assets/sounds/Voice/Moan4.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan5.wav", "assets/sounds/Voice/Moan5.wav");
			type.set ("assets/sounds/Voice/Moan5.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan6.wav", "assets/sounds/Voice/Moan6.wav");
			type.set ("assets/sounds/Voice/Moan6.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan7.wav", "assets/sounds/Voice/Moan7.wav");
			type.set ("assets/sounds/Voice/Moan7.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan8.wav", "assets/sounds/Voice/Moan8.wav");
			type.set ("assets/sounds/Voice/Moan8.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan9.wav", "assets/sounds/Voice/Moan9.wav");
			type.set ("assets/sounds/Voice/Moan9.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/data/chunk1.oel", "assets/data/chunk1.oel");
			type.set ("assets/data/chunk1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk10.oel", "assets/data/chunk10.oel");
			type.set ("assets/data/chunk10.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk2.oel", "assets/data/chunk2.oel");
			type.set ("assets/data/chunk2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk3.oel", "assets/data/chunk3.oel");
			type.set ("assets/data/chunk3.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk4.oel", "assets/data/chunk4.oel");
			type.set ("assets/data/chunk4.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk5.oel", "assets/data/chunk5.oel");
			type.set ("assets/data/chunk5.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk6.oel", "assets/data/chunk6.oel");
			type.set ("assets/data/chunk6.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk7.oel", "assets/data/chunk7.oel");
			type.set ("assets/data/chunk7.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk8.oel", "assets/data/chunk8.oel");
			type.set ("assets/data/chunk8.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/chunk9.oel", "assets/data/chunk9.oel");
			type.set ("assets/data/chunk9.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/dialogue.xml", "assets/data/dialogue.xml");
			type.set ("assets/data/dialogue.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/femboy.txt", "assets/data/femboy.txt");
			type.set ("assets/data/femboy.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/map.oep", "assets/data/map.oep");
			type.set ("assets/data/map.oep", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/start.oel", "assets/data/start.oel");
			type.set ("assets/data/start.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/tile_temple_0.png", "assets/data/tile_temple_0.png");
			type.set ("assets/data/tile_temple_0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_1.png", "assets/data/tile_temple_1.png");
			type.set ("assets/data/tile_temple_1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_2.png", "assets/data/tile_temple_2.png");
			type.set ("assets/data/tile_temple_2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_3.png", "assets/data/tile_temple_3.png");
			type.set ("assets/data/tile_temple_3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tile_temple_4.png", "assets/data/tile_temple_4.png");
			type.set ("assets/data/tile_temple_4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/aprilfools.png", "assets/images/aprilfools.png");
			type.set ("assets/images/aprilfools.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/batSheet.png", "assets/images/batSheet.png");
			type.set ("assets/images/batSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/clamSheet.png", "assets/images/clamSheet.png");
			type.set ("assets/images/clamSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/echidnaSheet.pdn", "assets/images/echidnaSheet.pdn");
			type.set ("assets/images/echidnaSheet.pdn", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/echidnaSheet.png", "assets/images/echidnaSheet.png");
			type.set ("assets/images/echidnaSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/echidnaSheet.txt", "assets/images/echidnaSheet.txt");
			type.set ("assets/images/echidnaSheet.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/edition.png", "assets/images/edition.png");
			type.set ("assets/images/edition.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hotGF.png", "assets/images/hotGF.png");
			type.set ("assets/images/hotGF.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/kirbyGF.png", "assets/images/kirbyGF.png");
			type.set ("assets/images/kirbyGF.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/left_and_right.png", "assets/images/left_and_right.png");
			type.set ("assets/images/left_and_right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/minotaurSheet.png", "assets/images/minotaurSheet.png");
			type.set ("assets/images/minotaurSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mmLogo.png", "assets/images/mmLogo.png");
			type.set ("assets/images/mmLogo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mushSheet.png", "assets/images/mushSheet.png");
			type.set ("assets/images/mushSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/picoDay.png", "assets/images/picoDay.png");
			type.set ("assets/images/picoDay.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/preloaderArt.png", "assets/images/preloaderArt.png");
			type.set ("assets/images/preloaderArt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/slimeSheet.png", "assets/images/slimeSheet.png");
			type.set ("assets/images/slimeSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/sonky.png", "assets/images/sonky.png");
			type.set ("assets/images/sonky.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/spr_player.png", "assets/images/spr_player.png");
			type.set ("assets/images/spr_player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/steveSheet.png", "assets/images/steveSheet.png");
			type.set ("assets/images/steveSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/trimmedAndFixedSprites.png", "assets/images/trimmedAndFixedSprites.png");
			type.set ("assets/images/trimmedAndFixedSprites.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/update-20180603T205106Z-001.zip", "assets/images/update-20180603T205106Z-001.zip");
			type.set ("assets/images/update-20180603T205106Z-001.zip", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/vineSheet.png", "assets/images/vineSheet.png");
			type.set ("assets/images/vineSheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/Silverline.ogg", "assets/music/Silverline.ogg");
			type.set ("assets/music/Silverline.ogg", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/music/Silverline.xmp", "assets/music/Silverline.xmp");
			type.set ("assets/music/Silverline.xmp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/flash.wav", "assets/sounds/flash.wav");
			type.set ("assets/sounds/flash.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/smack1.ogg", "assets/sounds/smack1.ogg");
			type.set ("assets/sounds/smack1.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/smack2.ogg", "assets/sounds/smack2.ogg");
			type.set ("assets/sounds/smack2.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/smack3.ogg", "assets/sounds/smack3.ogg");
			type.set ("assets/sounds/smack3.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan10.wav", "assets/sounds/Voice/Moan10.wav");
			type.set ("assets/sounds/Voice/Moan10.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan11.wav", "assets/sounds/Voice/Moan11.wav");
			type.set ("assets/sounds/Voice/Moan11.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan12.wav", "assets/sounds/Voice/Moan12.wav");
			type.set ("assets/sounds/Voice/Moan12.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan13.wav", "assets/sounds/Voice/Moan13.wav");
			type.set ("assets/sounds/Voice/Moan13.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan14.wav", "assets/sounds/Voice/Moan14.wav");
			type.set ("assets/sounds/Voice/Moan14.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan15.wav", "assets/sounds/Voice/Moan15.wav");
			type.set ("assets/sounds/Voice/Moan15.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan16.wav", "assets/sounds/Voice/Moan16.wav");
			type.set ("assets/sounds/Voice/Moan16.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan17.wav", "assets/sounds/Voice/Moan17.wav");
			type.set ("assets/sounds/Voice/Moan17.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan4.wav", "assets/sounds/Voice/Moan4.wav");
			type.set ("assets/sounds/Voice/Moan4.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan5.wav", "assets/sounds/Voice/Moan5.wav");
			type.set ("assets/sounds/Voice/Moan5.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan6.wav", "assets/sounds/Voice/Moan6.wav");
			type.set ("assets/sounds/Voice/Moan6.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan7.wav", "assets/sounds/Voice/Moan7.wav");
			type.set ("assets/sounds/Voice/Moan7.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan8.wav", "assets/sounds/Voice/Moan8.wav");
			type.set ("assets/sounds/Voice/Moan8.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Voice/Moan9.wav", "assets/sounds/Voice/Moan9.wav");
			type.set ("assets/sounds/Voice/Moan9.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/sounds/beep.ogg", "flixel/sounds/beep.ogg");
			type.set ("flixel/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/sounds/flixel.ogg", "flixel/sounds/flixel.ogg");
			type.set ("flixel/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/fonts/nokiafc22.ttf", "flixel/fonts/nokiafc22.ttf");
			type.set ("flixel/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/fonts/monsterrat.ttf", "flixel/fonts/monsterrat.ttf");
			type.set ("flixel/fonts/monsterrat.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/images/ui/button.png", "flixel/images/ui/button.png");
			type.set ("flixel/images/ui/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/images/logo/default.png", "flixel/images/logo/default.png");
			type.set ("flixel/images/logo/default.png", Reflect.field (AssetType, "image".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
